version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing NPM dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building Next.js application..."
      - npm run build
      - echo "Build completed successfully"
      - ls -la .next/
      - echo "Checking build artifacts..."
      - ls -la .next/standalone/ || echo "No standalone build found"

  post_build:
    commands:
      - echo "Post-build cleanup and optimization..."
      - echo "Removing development dependencies..."
      - rm -rf node_modules
      - echo "Installing production dependencies only..."
      - npm ci --omit=dev
      - echo "Creating deployment package..."
      - echo "Build completed at $(date)"

artifacts:
  files:
    - ".next/**/*"
    - "public/**/*"
    - "package.json"
    - "package-lock.json"
    - "next.config.js"
    - "appspec.yml"
    - "scripts/**/*"
    - "ecosystem.config.js"
    - "types/**/*"
    - ".env.example"
  name: ai-news-briefing-$(date +%Y-%m-%d-%H%M%S)
  base-directory: .
