version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing NPM dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building Next.js application..."
      - npm run build
      - echo "Build completed successfully"
      - ls -la .next/
      - echo "Checking build artifacts..."
      - ls -la .next/standalone/ || echo "No standalone build found"

  post_build:
    commands:
      - echo "Post-build cleanup and optimization..."
      - echo "Removing development dependencies..."
      - rm -rf node_modules
      - echo "Installing production dependencies only..."
      - npm ci --omit=dev
      - echo "Verifying deployment files..."
      - ls -la appspec.yml
      - ls -la scripts/
      - echo "Setting script permissions..."
      - chmod +x scripts/*.sh
      - echo "Verifying script permissions..."
      - ls -la scripts/install_dependencies.sh
      - ls -la scripts/start_server.sh
      - ls -la scripts/stop_server.sh
      - ls -la scripts/validate_service.sh
      - echo "Creating deployment package..."
      - echo "Build completed at $(date)"

artifacts:
  files:
    - ".next/**/*"
    - "public/**/*"
    - "package.json"
    - "package-lock.json"
    - "next.config.js"
    - "appspec.yml"
    - "scripts/install_dependencies.sh"
    - "scripts/start_server.sh"
    - "scripts/stop_server.sh"
    - "scripts/validate_service.sh"
    - "ecosystem.config.js"
    - "types/**/*"
    - ".env.example"
    - "node_modules/**/*"
  name: ai-news-briefing-$(date +%Y-%m-%d-%H%M%S)
  base-directory: .
