version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking GitHub source structure..."
      - ls -la
      - echo "Verifying Next.js project files..."
      - if [ -f "package.json" ]; then echo "✓ package.json found"; else echo "✗ package.json not found"; exit 1; fi
      - if [ -d "app" ]; then echo "✓ app directory found"; else echo "✗ app directory not found"; exit 1; fi
      - echo "Checking available source directories..."
      - ls -la $CODEBUILD_SRC_DIR_*/ 2>/dev/null || echo "No secondary sources found"
      - echo "Merging deployment files from S3 source..."
      - echo "Available environment variables:"
      - env | grep CODEBUILD_SRC_DIR || echo "No CODEBUILD_SRC_DIR variables found"
      - echo "Checking WebappSourceArtifacts contents:"
      - ls -la $CODEBUILD_SRC_DIR_WebappSourceArtifacts/ || echo "WebappSourceArtifacts directory not accessible"
      - echo "Copying appspec.yml and scripts from S3 artifact..."
      - cp $CODEBUILD_SRC_DIR_WebappSourceArtifacts/appspec.yml . || echo "Failed to copy appspec.yml from WebappSourceArtifacts"
      - cp -r $CODEBUILD_SRC_DIR_WebappSourceArtifacts/scripts . || echo "Failed to copy scripts from WebappSourceArtifacts"
      - echo "Listing all available source directories:"
      - find $CODEBUILD_SRC_DIR* -type d -maxdepth 1 2>/dev/null || echo "No source directories found"
      - echo "Setting script permissions..."
      - chmod +x scripts/*.sh 2>/dev/null || echo "No scripts found to set permissions"
      - echo "Final verification:"
      - ls -la appspec.yml 2>/dev/null && echo "✓ appspec.yml merged" || echo "✗ appspec.yml not found"
      - ls -la scripts/ 2>/dev/null && echo "✓ scripts directory merged" || echo "✗ scripts directory not found"

  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing NPM dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building Next.js application..."
      - npm run build
      - echo "Build completed successfully"
      - ls -la .next/
      - echo "Checking build artifacts..."
      - ls -la .next/standalone/ || echo "No standalone build found"

  post_build:
    commands:
      - echo "Post-build cleanup and optimization..."
      - echo "Removing development dependencies..."
      - rm -rf node_modules
      - echo "Installing production dependencies only..."
      - npm ci --omit=dev
      - echo "Verifying deployment files..."
      - ls -la appspec.yml
      - ls -la scripts/
      - echo "Setting script permissions..."
      - chmod +x scripts/*.sh
      - echo "Verifying script permissions..."
      - ls -la scripts/install_dependencies.sh
      - ls -la scripts/start_server.sh
      - ls -la scripts/stop_server.sh
      - ls -la scripts/validate_service.sh
      - echo "Creating deployment package..."
      - echo "Build completed at $(date)"

artifacts:
  files:
    - ".next/**/*"
    - "public/**/*"
    - "package.json"
    - "package-lock.json"
    - "next.config.js"
    - "appspec.yml"
    - "scripts/install_dependencies.sh"
    - "scripts/start_server.sh"
    - "scripts/stop_server.sh"
    - "scripts/validate_service.sh"
    - "ecosystem.config.js"
    - "types/**/*"
    - ".env.example"
    - "node_modules/**/*"
  name: ai-news-briefing-$(date +%Y-%m-%d-%H%M%S)
  base-directory: .
