version: '3.8'

services:
  ai-news-briefing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-news-briefing
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
    restart: unless-stopped
    volumes:
      - ./.env.local:/app/.env.local:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
